version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: front_pos
    container_name: front_pos
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: front_pos
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
       - ./:/var/www
       - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - front-pos-network
      - docker_db_network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: front_pos_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "81:80"
      - "444:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - front-pos-network

  #MySQL Service
  # db:
  #   image: mysql:5.7.22
  #   container_name: db
  #   restart: unless-stopped
  #   tty: true
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_DATABASE: admin
  #     MYSQL_ROOT_PASSWORD: password
  #     SERVICE_TAGS: dev
  #     SERVICE_NAME: mysql
  #   volumes:
  #     - dbdata:/var/lib/mysql
  #     - ./mysql/my.cnf:/etc/mysql/my.cnf
  #   networks:
  #     - app-network

#Docker Networks
networks:
  front-pos-network:
    driver: bridge
  docker_db_network:
    external: true

#Volumes
# volumes:
#   dbdata:
#     driver: local